### ISSUE TITLE
FirebaseAuth has no defer

### ISSUE THREAD

**Issue by leonardobazico** [soumak77/firebase-mock#23]
I'm trying to mock FirebaseAuth, but I got error cause has no _defer function in FirebaseAuth.

```bash
 TypeError: self._defer is not a function
      
      at defer (node_modules/firebase-mock/src/auth.js:39:10)
      at FirebaseAuth.Object.<anonymous>.FirebaseAuth.onAuthStateChanged (node_modules/firebase-mock/src/auth.js:31:3)
      at Function.init$ (app/services/Auth/auth.service.js:22:17)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:155:20)
      at node_modules/regenerator-runtime/runtime.js:165:13
      at tryCallOne (node_modules/promise/lib/core.js:37:12)
```

How can I implement this?

**Comment by soumak77** [comment]
@leonardobazico please provide a code sample

**Comment by soumak77** [comment]
Closing as inactive, please reopen with more information
