### ISSUE TITLE
mock-firebase with Jest testing

### ISSUE THREAD

**Issue by ntomallen** [soumak77/firebase-mock#36]
I have this react project setup with the infamous `create-react-app` project, and testing for that defaults to Jest, which gets the job done. I'm trying to test out a class I created to initialize a store for a certain firebase ref, like so: (I'm using mobx to handle observable stores)

`BadgeStore.js`
```
import { observable, action } from 'mobx'
import fb from '../firebaseConfig'

var db = fb.database()

class BdgeStore {
  constructor () {
    this.badges = observable({arr: new Array(0)})
  }

  @action.bound
  activate () {
    var badgesRef = db.ref('badges')
    badgesRef.on('value', (snapshot) => {
      this.badges.arr = new Array(0)
      snapshot.forEach(b => {
        // Make sure that the badge values exist:
        const badge = {
          name: b.val().name ? b.val().name : '',
          id: b.key
        }
        this.badges.arr.push(badge)
      })
    })
  }
}
var BadgeStore = new BdgeStore()
export default BadgeStore
```
Note that `fb` is an instance of firebase initialized with the web config API keys, etc. This works great, the application runs fine in firebase. For my test, I have the following:
`BadgeStore.test.js`
```
var proxyquire = require('proxyquire')
var firebasemock = require('firebase-mock')

var mockdatabase = new firebasemock.MockFirebase()
var mockauth = new firebasemock.MockFirebase()
var mocksdk = firebasemock.MockFirebaseSdk(function (path) {
  return mockdatabase.child(path)
}, function () {
  return mockauth
})

let BadgeStore = proxyquire('./BadgeStore', {
  fb: mocksdk
})
mockdatabase.flush()

describe('Badge Store', () => {
  it('constructs with an empty array', () => {
    expect(BadgeStore.badges.arr.length).toBe(0)
  })
  /* ... etc... */
}
```

Now, my problem is the following. When I run `npm test`, I get the following result in the console:
```
 FAIL  src\state\stores\BadgeStore.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'bind' of undefined

      at Proxyquire.Object.<anonymous>.Proxyquire.load(node_modules/proxyquire/lib/proxyquire.js:136:79)
      at Object.<anonymous> (src/state/stores/BadgeStore.test.js:16:18)
```

I'm not 100% sure what this means. Looking into the file, it seems as if it's not finding the firebase reference to replace? Help on this issue would be greatly appreciated. Thanks!

**Comment by elisechant** [comment]
You can use `jest.mock` instead of proxyquire.

I think you're looking for a snippet like this: 

```
jest.mock('app', () => {

	const firebasemock = require('firebase-mock');

	const mockdatabase = new firebasemock.MockFirebase();
	const mockauth = new firebasemock.MockFirebase();
	const mocksdk = new firebasemock.MockFirebaseSdk(path => {
		return path ? mockdatabase.child(path) : mockdatabase;
	}, () => {
		return mockauth;
	});

	const fb = mocksdk.initializeApp({
		config: {
			apiKey: "key-sjdfgjshdgf23",
			authDomain: "domain-jsdhfg2231",
			databaseURL: "db-djsfhjsyrr347",
			storageBucket: "bucket-wehruy6r2",
			messagingSenderId: "message-ui346578236"
		}
	});
	// console.log('fb', fb);
	// console.log('fb.database', fb.database().ref().once);
	return { // or however you're app initialisation looks like
		isMock: true,
		db: fb.database(),
		// auth: fb.auth(),
		// storage: fb.storage(),
		// messaging: fb.messaging(),
	}
});
import {get} from 'services/firebase';
describe('Firebase service ....
```

**Comment by soumak77** [comment]
@elisechant would you mind writing up a PR with this tutorial and link it to the main README like the others?

**Comment by elisechant** [comment]
yep no worries @soumak77. I'll do it early this week. 👍

**Comment by elisechant** [comment]
@ntomallen something like this might work for your code, using jest.mock in place of proxyquire: 
 
```
jest.mock('../firebaseConfig', () => {

  const firebasemock = require('firebase-mock');

  const mockdatabase = new firebasemock.MockFirebase();
  const mockauth = new firebasemock.MockFirebase();
  const mocksdk = new firebasemock.MockFirebaseSdk(path => {
    return path ? mockdatabase.child(path) : mockdatabase;
  }, () => {
    return mockauth;
  });

  const firebase = mocksdk.initializeApp(); // can take a path arg to database url
  // optional - expose the mock
  global.firebase = firebase;
  return firebase;
});

describe('Badge Store', () => {
  it('constructs with an empty array', () => {
    // ** expect firebase to be mocked here **
    expect(BadgeStore.badges.arr.length).toBe(0)
    // ...
```

**Comment by ntomallen** [comment]
Neat! I am consuming Firebase via a configuration file. (e.g., requiring that file gives me access to the already-initialized instance of Firebase.) [I'm using this package.](https://www.npmjs.com/package/firebase)

Just to be sure I understand this all properly, when I use jest.mock, I will have to implement each of the API calls to Firebase and return what I would expect my Firebase instance to return. Then, jest will automatically sub in the mock instead of using the real version when I run `npm test`. Is that right?

**Comment by soumak77** [comment]
Jest tutorial has been added.  I don't use it personally so please submit a PR for any necessary fixes.
