### ISSUE TITLE
Cannot read property replace of undefined when path is '/'

### ISSUE THREAD

**Issue by SidneyNemzer** [soumak77/firebase-mock#97]
```javascript
const firebaseMock = require("firebase-mock")

const mockdatabase = new firebaseMock.MockFirebase()
mockdatabase.child('/') //=> TypeError
```
[Runkit](https://runkit.com/embed/urww663xpl2x)

Stacktrace:
```
TypeError "Cannot read property 'replace' of undefined"
  at Object.mergePaths (node_modules/firebase-mock/src/utils.js:12:46)
  at MockFirebase.child (node_modules/firebase-mock/src/firebase.js:154:36)
```

Firebase JS SDK behavior:
```javascript
firebase.database().ref('/') //=> Reference
firebase.database().ref('/').child('/') //=> Reference
```
(Both reference the same path, "/")

**Comment by rhodgkins** [comment]
@soumak77 I've fixed #97 too, bear with!
